layer: configuration

language: typescript
platform: node

id: configs-commitlint

project:
  name: configs/commitlint
  description: commitlintの設定をまとめたパッケージです。

toolchain:
  typescript:
    routeOutDirToCache: false
