layer: configuration

language: typescript
platform: node

id: configs-eslint

project:
  name: configs/eslint
  description: "ESLintの設定をまとめたパッケージです。"

toolchain:
  typescript:
    routeOutDirToCache: false
